### ISSUE TITLE
Recursive values

### ISSUE THREAD

**Issue by cortpcl** [ryanlewis/seo-metadata#10]
Hi,

Is there a way i can get recursive values.

I tried adding a true in the end, like below.
 var metadata = Model.Content.GetPropertyValue<Epiphany.SeoMetadata.SeoMetadata>("metadata",true);
But that didnt seem to work.

**Comment by ryanlewis** [comment]
This will introduce some breaking changes, so this might have to be parked for a significant version bump for now.

The reason is that when you save the page, you get the default SeoMetadata JSON blob saved against the document. When you then ask for the property recursively it sees that it's set and uses that instead.

For now I would suggest creating a utility function that will return the field you want by checking whether it's empty or not, climbing the tree until it finds a field that isn't empty.
