### ISSUE TITLE
useDomainPrefixes Bug

### ISSUE THREAD

**Issue by croban** [ryanlewis/seo-metadata#18]
If useDomainPrefixes is set to true Google preview shows wrong url:
e.g.
http://localhosthttp://localhost:27911/

**Comment by ryanlewis** [comment]
Interesting, never used that setting before.

I'm on annual leave at the moment but will pick this up next week, and see if there's a way to grab that setting from an existing service.

**Comment by bjarnef** [comment]
It also has some issues in a multi-site (or multi-language) setup.

E.g. you might be logged in from mydomain1.com, but you are currently browsing the site with hostname mydomain2.com .. it should always use the hostname if one is added.

Furthermore I think at some point Umbraco changed something from relative urls to absolute urls. Previously I think you saw relative urls in properties tab, but now it is absolute urls.

**Comment by ryanlewis** [comment]
Is this just a display issue in the back office? Only a UrlSegmentProvider is implemented.

**Comment by bjarnef** [comment]
@ryanlewis yes, a display issue in the preview url. It confuse some clients because it always use the domain where you are logged in from, but is not ideal in a multi-site or multi-language setup.

e.g. login to mydomain1.com/umbraco

Site 1 (mydomain1.com)
Preview url: http://mydomain1.comhttp://mydomain1.com/ ...

Site 2 (mydomain2.com)
Preview url: http://mydomain1.comhttp://mydomain2.com/ ...

Site 3 (mydomain2.com)
Preview url: http://mydomain1.comhttp://mydomain3.com/ ...

Previously I think the urls you access from $parent just contains relative urls, but now (at least in our install) they are absolute urls.
It is fine to request current domain if no hostnames has been added, but otherwise I think it should use the first of the site specific domains.

**Comment by bjarnef** [comment]
I have submitted a PR for this here https://github.com/ryanlewis/seo-metadata/pull/20
It works better, but maybe take a look at what should happen when one enter special characters in urlName property.

**Comment by ryanlewis** [comment]
Resolved in ef0344425628564b7d7b96c69765a9e99b88d09d
