### ISSUE TITLE
System.Exception: Error unpacking extension

### ISSUE THREAD

**Issue by mastrup** [ryanlewis/seo-metadata#5]
When trying to install the extension in Umbraco (from a local package) I get the following error:

```
System.Exception: Error unpacking extension...
 ---> System.NullReferenceException:
Object reference not set to an instance of an object. at 
umbraco.cms.businesslogic.packager.Installer.LoadConfig(String tempDir) at 
umbraco.cms.businesslogic.packager.Installer.Import(String InputFile)
--- End of inner exception stack trace --- 
at umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) at 
umbraco.presentation.developer.packages.Installer.uploadFile(Object sender, EventArgs e)
```

Tested on Umbraco 7.2.4
![skaermbillede 2015-04-15 kl 20 45 19](https://cloud.githubusercontent.com/assets/3226788/7166797/5e055b58-e3b0-11e4-952f-aaeda79159b1.png)

**Comment by ryanlewis** [comment]
Think I've got an idea what this is - I suspect it's because the package.xml is missing the licence URL and it's falling over on [this line](https://github.com/umbraco/Umbraco-CMS/blob/ded1def8e2e7ea1a4fd0f849cc7a3f1f97cd8242/src/umbraco.cms/businesslogic/Packager/Installer.cs#L475).

I'll have a look at a fix for this tomorrow.

**Comment by ryanlewis** [comment]
Had a quick look - think I've resolved all the issues at the moment and the package should work now.

Grab [version 0.2.1](https://our.umbraco.org/projects/backoffice-extensions/seo-metadata-for-umbraco) of the package.

Let me know if that works for you.

**Comment by mastrup** [comment]
That did the trick!
